development:
  password: ${DEV_PASSWD}
  theme_id: ${DEV_THEMEID}
  store: ${DEV_SHOP}
  ignore_files:
    - config/settings_data.json

production:
  password: ${PROD_PASSWD}
  theme_id: ${PROD_THEMEID}
  store: ${PROD_SHOP}
  ignore_files:
    - config/settings_data.json
